### ISSUE TITLE
A new re-implementation for Structured Sparsity Learning

### ISSUE THREAD

**Issue by zjykzj** [lionminhu/structured-sparsity-learning#1]
HI @lionminhu , Thank you for your sharing. By studying your implementation, I have a better understanding of SSL.

By the way, I also implement [ZJCV/SSL](https://github.com/ZJCV/SSL), including `train-prune-finetuing` for VGGNet and ResNet

**Comment by lionminhu** [comment]
Hello, thank you for sharing!
I'll take a look at it later.
